### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [Anant-mishra1729/web-search#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Thanks!

**Comment by Anant-mishra1729** [comment]
I have now added the MIT License. Thank you for considering my plugin for inclusion in awesome-zsh-plugins, and please let me know if there are any other issues that need to be addressed.
